/*
 (c) Skimlinks 2009-2018
 Build time: Tue, 08 May 2018 07:03:28 GMT
 Version: 13.3.1
*/
(function(){function r(a){return"undefined"===typeof a||null===a}function w(a){if(r(a))return[];var c=[],e;for(e in a)Object.prototype.hasOwnProperty.call(a,e)&&c.push(e);return c}function k(a,c){var e=Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a);if(e)for(e=0;e<a.length;e++)c(a[e],e,a);else for(var b in a)Object.prototype.hasOwnProperty.call(a,b)&&c(a[b],b,a)}function x(){var a=arguments[0],c=Array.prototype.slice.call(arguments,1);r(a)&&(a={});k(c,function(c){r(c)&&
(c={});k(w(c),function(e){a[e]=c[e]})});return a}function t(a,c){var e=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments,0);return a.apply(c,e.concat(b))}}function y(a,c){var e=void 0;return function(){var b=this;clearTimeout(e);var d=Array.prototype.slice.call(arguments,0);e=setTimeout(function(){a.apply(b,d)},c)}}function b(a,c,e){var b=document.createElement(a),d="STYLE"===b.tagName;a="SCRIPT"===b.tagName;k(c||{},function(a,c){var e=c.split(".");
var d=b;if(d&&e&&e.length)for(var l=e.length,f=d,h=null,p=0;p<l;p++){var m=e[p];if(p===l-1){try{d[m]=a}catch(E){f[h]={},f[h][m]=a}break}m in d||(d[m]={});f=d;h=m;d=d[m]}});d&&(b.type="text/css");a&&(b.type="text/javascript");k([].concat(e||[]),function(a){var c="string"===typeof a;d&&c&&b.styleSheet?b.styleSheet.cssText+=a:(c&&(a=document.createTextNode(a)),b.appendChild(a))});return b}function z(a){var c=b("script",{src:"data:application/javascript;charset=utf-8;base64,dm9pZCAwOw==",onload:function(){a();
c.parentNode.removeChild(c)}});return c}function A(a){this.frameNode=b("iframe",{name:a.frameName,sandbox:"allow-popups allow-same-origin allow-scripts allow-top-navigation"});this.frameWrapper=b("div",{className:"skimconsent__centered-inner"},this.frameNode);return b("div",{"style.position":"fixed","style.top":"0px","style.right":"0px","style.bottom":"0px","style.left":"0px","style.zIndex":2147483647},[b("style",{},".skimconsent__centered-outer {\n    display: table !important;\n    position: absolute !important;\n    height: 100% !important;\n    width: 100% !important;\n    background-color: rgba(0, 0, 0, 0.3) !important;\n}\n.skimconsent__centered-middle {\n    display: table-cell !important;\n    vertical-align: middle !important;\n}\n.skimconsent__centered-inner {\n    position: relative !important;\n    margin-left: auto !important;\n    margin-right: auto !important;\n    width: calc(100% - 20px) !important;\n    max-width: 500px !important;\n    height: calc(100% - 60px);\n    overflow: hidden !important;\n    opacity: 1 !important;\n    visibility: hidden;\n}\n.skimconsent__centered-inner > iframe {\n    border: none;\n    width: 100% !important;\n    height: 100%;\n}\n\n@media only screen and (min-device-width: 768px) {\n    .skimconsent__centered-inner {\n        border-radius: 3px !important;\n    }\n}\n\n@media only screen and (max-device-width: 767px) {\n    .skimconsent__centered-outer {\n        background-color: #F1F6F7 !important;\n    }\n    .skimconsent__centered-inner {\n        width: 100% !important;\n        height: 100% !important;\n    }\n}\n"),
b("div",{className:"skimconsent__centered-outer"},b("div",{className:"skimconsent__centered-middle"},this.frameWrapper))])}function u(a){return a?a.charAt(0).toUpperCase()+a.slice(1):""}function B(a,c){for(var b=0;b<a.length;b++)if(c(a[b]))return a[b]}function C(){return B(n.getElementsByTagName("meta"),function(a){return"viewport"===a.name})}function D(a){var c=a.publisherDomain,e=a.merchantDomain,d=a.onResolve,g=a.onReject;a=a.onLoad;var l=f()?14:20,h=f()?20:12;l=c&&c.length<=l?u(c)+" uses cookies":
"We use cookies";e="continue to "+(e&&e.length<=h?e:"site");d=b("button",{className:"button button--primary",onclick:d},u(e));g=b("button",{className:"button button--secondary",onclick:g},"Do not accept");h=b("a",{href:"https://optout.skimlinks.com/",target:"_blank"},"data partners");var k=b("a",{href:"https://optout.skimlinks.com/",target:"_blank"},"here"),n=b("a",{href:"https://skimlinks.com/privacy-policy",target:"_blank"},"Privacy Policy");return b("div",{id:"root"},[b("link",{rel:"stylesheet",
href:"https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"}),b("style",{},['.row {\n    margin: -5px 0 0 -5px;\n    *zoom: 1;\n}\n.row:before,\n.row:after {\n    content: "";\n    display: table;\n}\n.row:after {\n    clear: both;\n}\n\n[class^="col-"], [class*=" col-"] {\n    float: left;\n    margin: 5px 0 0 5px;\n}\n.col-6 {\n    width: calc(50% - 5px);\n}\n\n@media only screen and (max-device-width: 767px) {\n    html:not(.ie) .col-12-sm {\n        width: calc(100% - 5px);\n    }\n}\n\n.spacer--vertical {\n    display: block;\n    width: 100%;\n    height: 10px;\n}\n',
"body {\n    background: #F1F6F7;\n    font-family: Arial, Helvetica, sans-serif;\n    font-size: 14px;\n    line-height: 1.5;\n}\nbody * {\n    box-sizing: border-box;\n}\nhtml, body, #root {\n    height: 100%;\n}\n.header {\n    text-align: center;\n    padding: 0 20px;\n    height: 50px;\n    line-height: 50px;\n    vertical-align: middle;\n    border-bottom: 1px solid #E1E9EC;\n}\n.title {\n    font-weight: bold;\n    font-size: 1.3rem;\n}\n.body {\n    padding: 15px 20px;\n}\n.footer {\n    display: table;\n    width: 100%;\n    padding: 0 20px;\n    height: 70px;\n    border-top: 1px solid #E1E9EC;\n}\n.footer__inner {\n    display: table-cell;\n    vertical-align: middle;\n}\n.button {\n    display: inline-block;\n    width: 100%;\n    padding: 7px 10px;\n    border-radius: 3px;\n    text-align: center;\n    text-decoration: none;\n}\n.button:focus {\n    outline: none;\n}\n.button:hover {\n    cursor: pointer;\n}\n.button--primary {\n    color: #FFF;\n    background-color: #0072CF;\n    border: 1px solid #0072CF;\n}\n.button--secondary {\n    color: #0088D8;\n    background-color: transparent;\n    border: 1px solid #9FB3B9;\n}\n\n/* MOBILE ONLY */\n@media only screen and (max-device-width: 767px) {\n    body {\n        font-size: 18px;\n    }\n    .body {\n        height: calc(100% - 50px - 130px);\n        min-height: 150px;\n        overflow-y: scroll;\n    }\n    .footer {\n        height: 130px;\n    }\n}\n"]),
b("div",{className:"header"},b("span",{className:"title"},l)),b("div",{className:"body"},["We invest time and money to bring you this content. It can only exist if we are able to earn money back after you\u2019ve read this content. ",b("b",{},(u(c)||"This website")+" and Skimlinks and its "),h," use cookies to collect and use data for ",b("b",{},"personalisation and selecting and showing ads and reporting"),'. By clicking "'+e+'", you indicate your consent for these cookies. You can withdraw your consent or read about your data rights and our legitimate interest on data usage ',
k,".",b("div",{className:"spacer--vertical"}),"Our partner's ",n]),b("div",{className:"footer"},b("div",{className:"footer__inner"},b("div",{className:"row"},[b("div",{className:"col-6 col-12-sm"},f()?d:g),b("div",{className:"col-6 col-12-sm"},f()?g:d)]))),z(a)])}function d(a){var c=this;0<d.instanceCount||(this.props=a,this.bindMethods(),this.root=A.call(this,{frameName:d.frameName}),n.body.appendChild(this.root),f()&&(this.initViewportMeta(),this.setViewportMetaTag()),this.frameDocument=this.frameNode.contentDocument||
this.frameNode.contentWindow.document,this.frameDocument.write('\x3c!--[if IE]><html class="ie"><![endif]--\x3e\x3c!--[if !IE]>\x3c!--\x3e<html>\x3c!--<![endif]--\x3e<head></head><body></body></html>'),a=D(x({},this.props,{onResolve:this.onResolve,onReject:this.onReject,onLoad:function(){c.adjustFrameHeight();c.bind()}})),this.frameDocument.body.appendChild(a),this.frameDocument.body.appendChild(this.props.anchorClone),d.instanceCount+=1)}var g=window.frames.top,v=0,q=window.frames.top,n=q.document,
f=function(a){var c=!1,b=void 0;return function(){if(c)return b;b=a.apply(this,arguments);c=!0;return b}}(function(){if(window.matchMedia&&"[object Function]"===Object.prototype.toString.call(window.matchMedia))var a=window.matchMedia("screen and (max-device-width: 767px)").matches;else{v+=1;var c="matchmedia-test-"+v;a=b("div",{id:c});c=b("div",{},[a,b("style",{},"\n@media screen and (max-device-width: 767px) {\n    #"+c+" {\n        width: 1px;\n    }\n}")]);document.body.appendChild(c);var d=!1;
try{d="1px"===("getComputedStyle"in window?window.getComputedStyle(a,null):a.currentStyle).width}catch(p){}c.parentNode.removeChild(c);a=d}return a});d.frameName="skimconsent";d.instanceCount=0;d.prototype.onResolve=function(a){var b=this;this.props.onResolve(a);setTimeout(function(){return b.destroy()},500)};d.prototype.onReject=function(a){var b=this;this.props.onReject(a);setTimeout(function(){return b.destroy()},500)};d.prototype.bindMethods=function(){this.adjustFrameHeight=y(t(this.adjustFrameHeight,
this),200);this.onResolve=t(this.onResolve,this);this.onReject=t(this.onReject,this)};d.prototype.adjustFrameHeight=function(){this.frameWrapper.style.visibility="hidden";this.frameWrapper.style.height="auto";this.frameNode.style.height="auto";var a=this.frameDocument.body.scrollHeight;this.frameWrapper.style.height=a<q.innerHeight?a+"px":"calc(100% - 60px)";this.frameNode.style.height="100%";this.frameWrapper.style.visibility="visible"};d.prototype.initViewportMeta=function(){var a=C();this.viewportMeta=
{originalNode:a,originalContent:a?a.content:"",temporaryNode:b("meta",{name:"viewport",content:""})}};d.prototype.setViewportMetaTag=function(){this.viewportMeta.originalNode?this.viewportMeta.originalNode.content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0":(this.viewportMeta.temporaryNode.content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0",n.head.appendChild(this.viewportMeta.temporaryNode))};d.prototype.resetViewportMetaTag=function(){this.viewportMeta.originalNode?
this.viewportMeta.originalNode.content=this.viewportMeta.originalContent:(this.viewportMeta.temporaryNode.content="",n.head.removeChild(this.viewportMeta.temporaryNode))};d.prototype.bind=function(){f()||q.addEventListener("resize",this.adjustFrameHeight)};d.prototype.unbind=function(){f()||q.removeEventListener("resize",this.adjustFrameHeight)};d.prototype.destroy=function(){var a=this;this.root.style.display="none";this.unbind();f()&&this.resetViewportMetaTag();setTimeout(function(){var b=a.root;
b.parentNode.removeChild(b);--d.instanceCount},0)};(function(a,b){g.__SKIM_JS_GLOBAL__||(g.__SKIM_JS_GLOBAL__={});g.__SKIM_JS_GLOBAL__.modules||(g.__SKIM_JS_GLOBAL__.modules={});g.__SKIM_JS_GLOBAL__.modules[a]=b})("ConsentA",d)})();
